spring:
  config:
    import: application-secret.yml  # ğŸ”¹ application-secret.yml íŒŒì¼ import
  application:
    name: monthlyzip
  profiles:
    active: secret
  devtools:
    restart:
      enabled: true  # ?? ?? ?? ? ???
    livereload:
      enabled: true  # ????? ?? ? ????

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    p6spy: info   # âœ… ë§ˆì§€ë§‰ ì‹¤í–‰ëœ SQLë§Œ ì¶œë ¥
    org.hibernate.SQL: info  # Hibernate ê¸°ë³¸ SQL ë¡œê·¸ ì¤„ì´ê¸°
    root: INFO
    com.monthlyzip: DEBUG  # âœ… í”„ë¡œì íŠ¸ íŒ¨í‚¤ì§€ì— ëŒ€í•´ DEBUG ë ˆë²¨ ì ìš©
